"""Scoring and triage banding for the v2 screening app.

**Why there is no machine-learning model here.** v1 ships `model_d9.joblib`, a
`CalibratedClassifierCV` over an SVC trained on `SLE_NotSLE.csv` — a 202/200 case-control
cohort of hospital patients. Evaluated across all 128 possible d9 inputs, it returns
**0.921 with no symptoms ticked**, places 117/128 inputs in the highest risk band, and is
non-monotonic: reporting an isolated fever *lowers* its output to 0.185. That behaviour is
correct for its training cohort, where the comparison group was other sick people, and
invalid for a public booth, where the comparison group is healthy people. It is therefore
not used for scoring. See README.md.

v2 uses a **points table fitted to that cohort but shrunk toward the published EULAR/ACR
2019 weights**, summed rather than reduced by the domain-maximum rule. The weights live in
`criteria_d9.json` as `score`, alongside the published value as `eular_score`; they are
regenerated by `exp/fit_points_model.py`. The score is monotonic by construction (every
weight is positive), scores 0 when nothing is present, and its derivation is a stated
assumption rather than a black box. See README.md for why the published weights alone were
not kept.

This module does not import Streamlit, so it can be unit-tested and reused from analysis
scripts.
"""

from __future__ import annotations

import json
from pathlib import Path

APP_VERSION = "2.0.0"

_HERE = Path(__file__).parent
CRITERIA_FILE = _HERE / "criteria_d9.json"
ARTICLE_FILE = _HERE / "article_th.md"

# Triage cut-offs on the fitted points score, which ranges 0–36 for these seven criteria.
#
# The four bands were chosen so that each carries a distinct likelihood ratio on the
# derivation cohort, rather than by splitting the range evenly:
#
#   GREEN  0–2    LR 0.14   nothing, or only an isolated vague finding
#   YELLOW 3–7    LR 0.93   findings present but non-specific — this band is deliberately
#                           *uninformative*, and must not be reported as reassurance
#   ORANGE 8–12   LR 10.1   refer, non-urgently
#   RED    13+    LR ≥35    refer promptly; 0 of 202 controls reached this band
#
# Referral starts at ORANGE. YELLOW exists precisely because a score of 3–7 leaves risk
# unchanged: those visitors must not be told they are clear, but referring them would mean
# referring one control for every case found. See exp/REPORT.md.
#
# PROVISIONAL — these need clinical sign-off, and should be revisited after the first
# event against the real distribution of booth scores and the referral clinic's capacity.
BAND_YELLOW = 3
BAND_ORANGE = 8
BAND_RED = 13

GREEN, YELLOW, ORANGE, RED = "green", "yellow", "orange", "red"

# Ascending severity, so callers can compare bands without hardcoding the order.
BAND_ORDER = (GREEN, YELLOW, ORANGE, RED)

# Cross-validated performance of the shipped table at the ORANGE referral cut-off, over 50
# outer folds, refitting the weights inside each fold. These are measured output, not
# tuning knobs — regenerate with exp/fit_points_model.py rather than editing them.
SENSITIVITY_AT_REFERRAL = 0.802
SPECIFICITY_AT_REFERRAL = 0.966

# The same procedure with the Proteinuria column zeroed at prediction time, i.e. what the
# table is worth to a visitor with no urine result. Proteinuria carries 12 of the 36
# points, and 37 of the cohort's 200 SLE patients present with it and nothing else, so
# more than half the sensitivity depends on that one dipstick.
SENSITIVITY_WITHOUT_URINE = 0.378


def load_criteria() -> list[dict]:
    """Load the seven d9 criteria.

    Returns:
        The criteria as stored in `criteria_d9.json`, in display order.
    """
    with open(CRITERIA_FILE, encoding="utf-8") as f:
        return json.load(f)


def load_article() -> str:
    """Load the บทความ page content.

    Written by the project team rather than reproduced from elsewhere, so that publishing
    it needs nobody's permission — see docs/adr/0001-third-party-poster-usage.md. Kept as
    Markdown so a clinician can review and edit it without touching code.

    Returns:
        The Markdown source of `article_th.md`.
    """
    return ARTICLE_FILE.read_text(encoding="utf-8")


def max_score(criteria: list[dict]) -> int:
    """Highest total reachable, i.e. every criterion ticked.

    Args:
        criteria: The criteria list from `load_criteria()`.

    Returns:
        The sum of every weight.
    """
    return sum(c["score"] for c in criteria)


def compute_score(values: dict[str, bool], criteria: list[dict]) -> tuple[int, dict[str, int]]:
    """Add up the weights of the ticked criteria.

    Every present criterion contributes, unlike the EULAR/ACR domain-maximum rule this
    replaced. That rule exists to stop one organ system dominating a *classification*
    score; for screening it discards information, and here it hid the fact that two
    mucocutaneous findings together are stronger evidence than either alone.

    Args:
        values: Maps criterion `key` to whether it was ticked. Missing keys read as absent.
        criteria: The criteria list from `load_criteria()`.

    Returns:
        `(total, breakdown)` where `breakdown` maps each domain present in `criteria` to
        the points its ticked criteria contributed. Domains contributing nothing map to 0.
    """
    breakdown: dict[str, int] = {c["domain"]: 0 for c in criteria}
    for c in criteria:
        if values.get(c["key"], False):
            breakdown[c["domain"]] += c["score"]
    return sum(breakdown.values()), breakdown


def compute_band(score: int) -> str:
    """Map a points total onto a triage band.

    Args:
        score: Total from `compute_score`.

    Returns:
        One of `GREEN`, `YELLOW`, `ORANGE`, `RED`.
    """
    if score >= BAND_RED:
        return RED
    if score >= BAND_ORANGE:
        return ORANGE
    if score >= BAND_YELLOW:
        return YELLOW
    return GREEN
